#!/usr/bin/env node
/**
 * Fumadocs -> Mintlify content migration.
 *
 * Moves docs-old/content/docs/** to the repo root, preserving URLs:
 *   - strips the `content/docs` prefix
 *   - renames `<folder>/index.mdx` -> `<folder>.mdx`
 * and mechanically rewrites the high-frequency component syntax.
 *
 * API-reference operation pages (those using <APIPage> / _openapi frontmatter)
 * are SKIPPED here and regenerated by migrate-openapi.mjs. The 4 hand-written
 * api-reference pages (index/rate-limiting/idempotency/payload-limits) are moved.
 *
 * Usage: node migration/migrate-content.mjs [--dry]
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'docs-old', 'content', 'docs');
const DRY = process.argv.includes('--dry');

const report = {
  moved: 0,
  skippedApi: 0,
  customComponents: {}, // component -> [files]
  unmappedIcons: {}, // icon -> count
};

// ---- brand icon mapping: custom SVG icon components -> Font Awesome brand names.
// Lucide-style PascalCase icons (Brain, Zap, Rocket, ...) are kebab-cased automatically.
const BRAND_MAP = {
  NextjsIcon: 'node-js', ExpressjsIcon: 'node-js', RemixIcon: 'react',
  NestjsIcon: 'node-js', SvelteIcon: 'js', NuxtIcon: 'vuejs', VueIcon: 'vuejs',
  ReactIcon: 'react', AngularIcon: 'angular', NodeIcon: 'node-js', PhpIcon: 'php',
  PythonIcon: 'python', GoIcon: 'golang', GolangIcon: 'golang', JavaIcon: 'java',
  RubyIcon: 'gem', DotnetIcon: 'microsoft', TypescriptIcon: 'js', JavascriptIcon: 'js',
  LaravelIcon: 'laravel', KotlinIcon: 'android', H3Icon: 'node-js', LambdaIcon: 'aws',
  ClerkIcon: 'react', StripeIcon: 'stripe', SegmentIcon: 'chart-simple',
};

// PascalCase / camelCase -> kebab-case (Lucide icon naming). Code2 -> code-2.
function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Za-z])([0-9])/g, '$1-$2')
    .toLowerCase();
}

// Resolve an icon component/name to a Mintlify icon string.
function iconNameFor(comp) {
  if (BRAND_MAP[comp]) return BRAND_MAP[comp];
  if (comp.endsWith('Icon') && BRAND_MAP[comp]) return BRAND_MAP[comp];
  // unknown *Icon brand component -> best-effort kebab of its base
  if (comp.endsWith('Icon')) return kebab(comp.replace(/Icon$/, ''));
  // Lucide-style component name
  return kebab(comp);
}

// Standard MDX component imports that are Mintlify globals -> strip the import line
const STRIP_IMPORT_NAMES = new Set([
  'Tab', 'Tabs', 'Step', 'Steps', 'Accordion', 'Accordions',
  'Callout', 'TypeTable', 'File', 'Files', 'Folder', 'Card', 'Cards',
]);

// Custom components we cannot mechanically convert -> record for the long-tail pass
const CUSTOM_COMPONENTS = [
  'EmailProviderNextSteps', 'ChangelogDisplay', 'OverviewPage', 'CodeTemplateBlock',
  'StudioStep', 'TestStep', 'PackagesStep', 'SecretStep', 'WorkflowStep',
  'NextStepsStep', 'DeployApp', 'TypeTable', 'File', 'Files', 'Folder', 'Button',
];

// fix internal links that were already broken/stale in the old source
const LINK_FIXES = {
  '/api-reference/notifications/list-all-notifications': '/api-reference/notifications/list-all-events',
  '/platform/inbox/customization-and-configuration/inbox-with-context': '/platform/inbox/configuration/inbox-with-context',
  '/images/channels-and-providers/email/writing-email-template/show-block.gif':
    '/images/workflows/add-notification-content/channels-template-editors/show-block.gif',
  '/agents/operate/deploy-with-github-actions': '/agents/custom-code-agent/going-to-production',
};

// load authored MDX replacements for the custom snippet/grid components
const SNIPPET_DIR = path.join(import.meta.dirname, 'snippets');
const SNIPPETS = {};
for (const f of fs.readdirSync(SNIPPET_DIR)) {
  SNIPPETS[f.replace(/\.md$/, '')] = fs.readFileSync(path.join(SNIPPET_DIR, f), 'utf8').trimEnd();
}

function walk(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else if (entry.name.endsWith('.mdx') && !entry.name.endsWith('.model.mdx')) acc.push(full);
  }
  return acc;
}

function targetPath(srcFile) {
  let rel = path.relative(SRC, srcFile); // e.g. platform/workflow/index.mdx
  // strip Fumadocs route-group segments like (providers) — removed from the URL
  rel = rel.split(path.sep).filter((seg) => !/^\(.*\)$/.test(seg)).join(path.sep);
  // rename folder index -> folder.mdx (one level up)
  if (rel.endsWith(path.sep + 'index.mdx')) {
    rel = rel.slice(0, -(path.sep + 'index.mdx').length) + '.mdx';
  } else if (rel === 'index.mdx') {
    rel = 'index.mdx'; // site root stays index.mdx
  }
  return path.join(ROOT, rel);
}

function splitFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { fm: null, body: raw };
  return { fm: m[1], body: raw.slice(m[0].length) };
}

// keep only Mintlify-meaningful frontmatter keys
function rewriteFrontmatter(fm) {
  if (fm == null) return null;
  const keep = ['title', 'description', 'sidebarTitle', 'icon'];
  const lines = fm.split('\n');
  const out = [];
  let curKey = null;
  for (const line of lines) {
    const km = line.match(/^(\w[\w-]*):/);
    if (km) {
      curKey = km[1];
      if (curKey === 'icon') {
        // normalize Lucide/FA icon name to kebab-case (e.g. "CircleHelp" -> "circle-help")
        const iv = line.match(/^icon:\s*['"]?([^'"]+)['"]?\s*$/);
        if (iv && /[A-Z]/.test(iv[1])) { out.push(`icon: "${kebab(iv[1].trim())}"`); continue; }
        out.push(line);
      } else if (curKey === 'title' || curKey === 'sidebarTitle') {
        // strip JSX from titles (e.g. "Setup the <Subscription />" -> "Setup the Subscription")
        out.push(line.replace(/<\/?([A-Za-z][\w]*)[^>]*\/?>/g, '$1').replace(/\s+(['"])\s*$/, '$1').replace(/[ \t]{2,}/g, ' '));
      } else if (keep.includes(curKey)) out.push(line);
    } else if (curKey && keep.includes(curKey) && /^\s+/.test(line)) {
      out.push(line); // continuation of a kept multiline value
    }
  }
  return out.join('\n');
}

// Strip top-level component/icon/snippet imports, preserving code-fence content.
// Drops imports whose module specifier is a local repo path (@/, ./, ../, /snippets,
// fumadocs-*) or whose named imports are all Mintlify global components.
function stripComponentImports(s) {
  const fences = [];
  let masked = s.replace(/(^|\n)(```|~~~)[^\n]*\n[\s\S]*?\n[ \t]*\2[ \t]*(?=\n|$)/g, (m) => {
    fences.push(m);
    return `\uE000F${fences.length - 1}\uE000`;
  });
  // Mintlify only supports importing local snippets from /snippets; strip every other
  // top-level import (component libs, icon libs, SDK aliases — all unresolvable here).
  masked = masked.replace(/^[ \t]*import\b[\s\S]*?from\s*['"]([^'"]+)['"];?[ \t]*$/gm, (full, mod) =>
    /^\/snippets/.test(mod) ? full : ''
  );
  return masked.replace(/\uE000F(\d+)\uE000/g, (m, i) => fences[Number(i)]);
}

// run a transform only on text outside fenced code blocks
function outsideFences(s, fn) {
  const fences = [];
  let masked = s.replace(/(^|\n)([ \t]*)(```|~~~)[^\n]*\n[\s\S]*?\n[ \t]*\3[ \t]*(?=\n|$)/g, (m, pre) => {
    fences.push(m.slice(pre.length));
    return `${pre}\uE000${fences.length - 1}\uE000`;
  });
  masked = fn(masked);
  return masked.replace(/\uE000(\d+)\uE000/g, (m, i) => fences[Number(i)]);
}

function recordCustom(file, name) {
  (report.customComponents[name] ||= []).push(path.relative(ROOT, file));
}

function transformBody(body, file) {
  let s = body;

  // 1. Strip MDX component/icon/snippet import statements (Mintlify can't resolve
  //    local repo imports and provides components as globals). Fence-aware so SDK
  //    imports inside ```code``` examples are preserved. Multiline-aware.
  s = stripComponentImports(s);

  // 2. Callout -> Note / Warning  (info/default -> Note, warn/error -> Warning)
  const calloutTag = (attrs) => {
    const t = (attrs.match(/type\s*=\s*['"](\w+)['"]/) || [])[1] || 'info';
    return t === 'warn' || t === 'error' ? 'Warning' : 'Note';
  };
  const calloutTitle = (attrs) => (attrs.match(/title\s*=\s*["']([^"']*)["']/) || [])[1];
  // 2a. block callouts (tag begins a line): keep open/close at the SAME indentation,
  //     preserve inner content indentation (MDX needs matching nesting in list items).
  s = s.replace(/^([ \t]*)<Callout\b([^>]*)>([\s\S]*?)<\/Callout>[ \t]*$/gm, (m, indent, attrs, inner) => {
    const tag = calloutTag(attrs);
    const title = calloutTitle(attrs);
    const base = indent + '  ';
    const lines = inner.replace(/^\s*\n/, '').replace(/\n\s*$/, '').split('\n');
    const nonEmpty = lines.filter((l) => l.trim());
    // shift the whole block so its minimum indent becomes base (preserves relative indent)
    const min = nonEmpty.length ? Math.min(...nonEmpty.map((l) => l.match(/^[ \t]*/)[0].length)) : 0;
    const body = lines.map((l) => (l.trim() ? base + l.slice(min) : '')).join('\n');
    const titleLine = title ? `${base}**${title}**\n\n` : '';
    return `${indent}<${tag}>\n${titleLine}${body}\n${indent}</${tag}>`;
  });
  // 2b. inline callouts (mid-line / single line): collapse to one line
  s = s.replace(/<Callout\b([^>]*)>([\s\S]*?)<\/Callout>/g, (m, attrs, inner) => {
    const tag = calloutTag(attrs);
    const title = calloutTitle(attrs);
    const body = inner.replace(/\s+/g, ' ').trim();
    return `<${tag}>${title ? `**${title}** ` : ''}${body}</${tag}>`;
  });

  // 3. Tabs: remove items={[...]} attr; <Tab value="X"> -> <Tab title="X">
  s = s.replace(/<Tabs\b[^>]*>/g, '<Tabs>');
  s = s.replace(/<Tab\s+value\s*=\s*(['"])(.*?)\1\s*>/g, '<Tab title=$1$2$1>');

  // 4. Cards -> Columns ; Card icon={<XIcon/>} -> icon="name"
  s = s.replace(/<Cards\b[^>]*>/g, '<Columns cols={2}>');
  s = s.replace(/<\/Cards>/g, '</Columns>');
  s = s.replace(/icon=\{<(\w+)[^}]*?\/>\}/g, (full, comp) => {
    if (!BRAND_MAP[comp] && comp.endsWith('Icon')) report.unmappedIcons[comp] = (report.unmappedIcons[comp] || 0) + 1;
    return `icon="${iconNameFor(comp)}"`;
  });

  // 4b. next/link <Link href> -> <a href> (Mintlify has no Link component)
  s = s.replace(/<Link(\s[^>]*)?>/g, '<a$1>').replace(/<\/Link>/g, '</a>');

  // 4c. <Method href="X">label</Method> (custom inline link) -> markdown link
  s = s.replace(/<Method\s+href=(["'])(.*?)\1\s*>([\s\S]*?)<\/Method>/g, (m, q, href, label) => {
    const text = label.replace(/\{`([^`]*)`\}/g, '`$1`').replace(/\s+/g, ' ').trim();
    return `[${text}](${href})`;
  });

  // 4d. raw <a href>TEXT</a> with text-only content -> markdown link (cleaner + a11y:
  //     code-only link text like <a>`x`</a> isn't seen as accessible text). Skips
  //     anchors wrapping nested HTML (e.g. images) and anything inside code fences.
  s = outsideFences(s, (x) =>
    x.replace(/<a\s+[^>]*?href=(["'])(.*?)\1[^>]*>([^<]+)<\/a>/g, (m, q, href, text) => `[${text.trim()}](${href})`)
  );

  // 5. Accordions -> AccordionGroup
  s = s.replace(/<Accordions\b[^>]*>/g, '<AccordionGroup>');
  s = s.replace(/<\/Accordions>/g, '</AccordionGroup>');

  // 6. Tooltip directive :tooltip[text]{label="..."} -> <Tooltip tip="...">text</Tooltip>
  s = s.replace(/:tooltip\[([^\]]*)\]\{label\s*=\s*"([^"]*)"\}/g,
    (full, text, label) => `<Tooltip tip="${label.replace(/"/g, '&quot;')}">${text}</Tooltip>`);

  // 7. Strip Shiki line-marker comments [!code ...] (no Mintlify equivalent)
  s = s.replace(/\s*\/\/\s*\[!code[^\]]*\]/g, '');
  s = s.replace(/\s*\{\/\*\s*\[!code[^\]]*\]\s*\*\/\}/g, '');
  s = s.replace(/#\s*\[!code[^\]]*\]/g, '');

  // 6a. File tree (<Files>/<Folder>/<File>) -> code-block ASCII tree
  s = s.replace(/<Files>([\s\S]*?)<\/Files>/g, (m, inner) => {
    const out = [];
    let depth = 0;
    for (const line of inner.split('\n')) {
      let mm;
      if ((mm = line.match(/<Folder\s+name=["']([^"']+)["']/))) { out.push('  '.repeat(depth) + mm[1] + '/'); depth++; }
      else if (/<\/Folder>/.test(line)) depth = Math.max(0, depth - 1);
      else if ((mm = line.match(/<File\s+name=["']([^"']+)["']/))) out.push('  '.repeat(depth) + mm[1]);
    }
    return '```\n' + out.join('\n') + '\n```';
  });

  // 6a2. CodeTemplateBlock / ChangelogDisplay -> Note (no Mintlify equivalent)
  s = s.replace(/<CodeTemplateBlock\s+templateId=["']([^"']+)["']\s*\/>/g,
    (m, id) => `<Note>\n  Explore the full \`${id}\` example in the [Novu examples repository](https://github.com/novuhq/novu).\n</Note>`);
  s = s.replace(/<ChangelogDisplay\s*\/>/g,
    `<Note>\n  See the [@novu/react releases](https://github.com/novuhq/novu/releases) for the full changelog.\n</Note>`);

  // 6b. TypeTable -> markdown table (prop reference)
  s = s.replace(/<TypeTable\b[^>]*?type=\{\{([\s\S]*?)\}\}\s*\/>/g, (m, body) => {
    const rows = [];
    const propRe = /(['"]?)([A-Za-z0-9_$]+)\1\s*:\s*\{([^}]*)\}/g;
    let pm;
    while ((pm = propRe.exec(body))) {
      const name = pm[2];
      const inner = pm[3];
      const get = (k) => (inner.match(new RegExp(`${k}\\s*:\\s*['"]([^'"]*)['"]`)) || [])[1] || '';
      const type = get('type') || get('typeDescription');
      let desc = get('description');
      const def = get('default');
      if (def) desc += `${desc ? ' ' : ''}(default: \`${def}\`)`;
      rows.push(`| \`${name}\` | ${type ? `\`${type}\`` : ''} | ${desc.replace(/\|/g, '\\|')} |`);
    }
    return rows.length ? `| Property | Type | Description |\n| --- | --- | --- |\n${rows.join('\n')}` : m;
  });

  // 6c. Inline the custom snippet/grid components with authored MDX equivalents
  for (const [name, content] of Object.entries(SNIPPETS)) {
    s = s.replace(new RegExp(`^[ \\t]*<${name}\\b[^>]*\\/>[ \\t]*$`, 'gm'), `\n${content}\n`);
  }

  // 7b. Fix internal links that were already stale/broken in the old source
  for (const [from, to] of Object.entries(LINK_FIXES)) s = s.split(from).join(to);

  // 8. Record remaining custom components for long-tail pass
  for (const name of CUSTOM_COMPONENTS) {
    const re = new RegExp(`<${name}\\b`);
    if (re.test(s)) recordCustom(file, name);
  }

  return s;
}


// copy co-located non-mdx assets (e.g. media-assets/**) preserving relative paths
function copyAssets(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) copyAssets(full);
    else if (!e.name.endsWith('.mdx') && e.name !== 'meta.json') {
      let rel = path.relative(SRC, full).split(path.sep).filter((s) => !/^\(.*\)$/.test(s)).join(path.sep);
      const dest = path.join(ROOT, rel);
      if (!DRY) { fs.mkdirSync(path.dirname(dest), { recursive: true }); fs.copyFileSync(full, dest); }
    }
  }
}
if (!DRY) copyAssets(SRC);

// ---- main
const files = walk(SRC);
for (const file of files) {
  const rel = path.relative(SRC, file);
  const raw = fs.readFileSync(file, 'utf8');

  // Skip generated API operation pages (regenerated separately)
  const isApiRef = rel.startsWith('api-reference' + path.sep);
  const isManualApi = /^api-reference[\\/](index|rate-limiting|idempotency|payload-limits)\.mdx$/.test(rel);
  if (isApiRef && !isManualApi) {
    if (/<APIPage\b/.test(raw) || /_openapi:/.test(raw)) { report.skippedApi++; continue; }
  }

  const { fm, body } = splitFrontmatter(raw);
  const newFm = rewriteFrontmatter(fm);
  const newBody = transformBody(body, file);
  const out = (newFm != null ? `---\n${newFm}\n---\n` : '') + newBody.replace(/\n{3,}/g, '\n\n');

  const dest = targetPath(file);
  if (!DRY) {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, out);
  }
  report.moved++;
}

// ---- write report
const reportPath = path.join(ROOT, 'migration', 'content-report.json');
const summary = {
  moved: report.moved,
  skippedApiOperationPages: report.skippedApi,
  unmappedIcons: report.unmappedIcons,
  customComponentCounts: Object.fromEntries(
    Object.entries(report.customComponents).map(([k, v]) => [k, v.length])
  ),
  customComponentFiles: report.customComponents,
};
if (!DRY) fs.writeFileSync(reportPath, JSON.stringify(summary, null, 2));
console.log(JSON.stringify({ ...summary, customComponentFiles: undefined }, null, 2));
console.log(DRY ? '(dry run — nothing written)' : `report -> migration/content-report.json`);
